# =============================================================================
# RDS PostgreSQL Single-AZ (4B) - free-tier compatible
# =============================================================================
# Generate master password locally - cross-region replica is incompatible
# with manage_master_user_password (Secrets Manager).
resource "random_password" "master" {
  length      = 24
  special     = true
  min_lower   = 2
  min_upper   = 2
  min_numeric = 2
  # PostgreSQL master password forbids these characters
  override_special = "!#$%&*+-=?^_"
}

resource "aws_secretsmanager_secret" "master" {
  name        = "${var.project_name}-rds-master"
  description = "Master password for ${var.project_name} RDS (generated by Terraform)"
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
  })
}

# Original plan: Aurora 1 Writer + 2 Reader, 3 AZ.
# Free-tier account does not allow Aurora clusters or Multi-AZ DB Clusters.
# Falling back to single instance RDS PostgreSQL (db.t3.micro, gp3 20 GB).
#
# Trade-off acknowledged for the demo:
#   - Lose: read replicas, multi-AZ failover, reader endpoint
#   - Keep: encrypted storage, Secrets Manager managed password,
#           same security group + cross-VPC access via TGW,
#           same connection workflow from Bastion
# When presenting, frame this as "scope-down for free-tier; production
# would use Multi-AZ DB Cluster or Aurora with 2 read replicas."
# =============================================================================

resource "aws_db_instance" "main" {
  identifier = "${lower(var.project_name)}-postgres"

  engine         = var.engine
  engine_version = var.engine_version
  port           = var.port

  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage
  storage_type      = var.storage_type
  storage_encrypted = true

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result

  # NOTE: not using manage_master_user_password=true because RDS PostgreSQL
  # does NOT support cross-region read replicas from a source with
  # Secrets-Manager-managed password (AWS limitation, see Phase 5B). The
  # password is generated by Terraform and stored in tfstate (sensitive).

  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = [var.security_group_id]
  publicly_accessible    = false
  multi_az               = false # Single-AZ for free tier

  backup_retention_period      = 1
  backup_window                = "17:00-18:00"
  maintenance_window           = "sun:18:00-sun:19:00"
  auto_minor_version_upgrade   = true
  performance_insights_enabled = false

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = { Name = "${var.project_name}-RDS-Postgres" }
}
