# =============================================================================
# Aurora PostgreSQL (4B) - 1 Writer + 2 Reader across 3 AZ in VPC Data
# =============================================================================
# Original plan restored (see [NT113] Architecture diagram.png):
#   - Aurora PostgreSQL cluster, 1 Writer + 2 Reader, one instance per AZ
#   - Part of an Aurora Global Database so Phase 5B can attach a cross-region
#     secondary cluster in ap-southeast-2 (replaces the old RDS read replica)
#
# NOTE on free-tier: Aurora is NOT free-tier eligible and db.t3.micro is not a
# valid Aurora instance class. The smallest Aurora class is db.t3.medium.
# =============================================================================

# Master password generated locally and stored in Secrets Manager.
resource "random_password" "master" {
  length      = 24
  special     = true
  min_lower   = 2
  min_upper   = 2
  min_numeric = 2
  # PostgreSQL master password forbids these characters
  override_special = "!#$%&*+-=?^_"
}

resource "aws_secretsmanager_secret" "master" {
  name        = "${var.project_name}-aurora-master"
  description = "Master password for ${var.project_name} Aurora (generated by Terraform)"

  # Demo: don't keep secret in pending-deletion state - allow terraform destroy
  # to truly remove it so apply right after destroy doesn't conflict.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
  })
}


# -----------------------------------------------------------------------------
# 1. Aurora Global Database container
# The global cluster is the cross-region grouping. The primary cluster below
# joins it; Phase 5B (database_dr) attaches a secondary cluster in the DR region.
# -----------------------------------------------------------------------------
resource "aws_rds_global_cluster" "main" {
  global_cluster_identifier = "${lower(var.project_name)}-aurora-global"
  engine                    = var.engine
  engine_version            = var.engine_version
  storage_encrypted         = true

  # database_name is intentionally NOT set here. When you create the global
  # cluster from scratch and then ATTACH a primary cluster (our flow), the
  # global cluster's database_name is not propagated to the primary - the DB is
  # only actually created when database_name is set on the primary aws_rds_cluster.
}


# -----------------------------------------------------------------------------
# 2. Primary Aurora cluster (in this region's VPC Data)
# -----------------------------------------------------------------------------
resource "aws_rds_cluster" "main" {
  cluster_identifier        = "${lower(var.project_name)}-aurora"
  global_cluster_identifier = aws_rds_global_cluster.main.id

  engine         = var.engine
  engine_version = var.engine_version
  port           = var.port

  # database_name MUST be on the primary cluster - this is what actually creates
  # the initial database. The DR secondary inherits it via replication.
  database_name   = var.database_name
  master_username = var.master_username
  master_password = random_password.master.result

  db_subnet_group_name   = var.db_subnet_group_name # 3-AZ subnet group from vpc_data
  vpc_security_group_ids = [var.security_group_id]
  storage_encrypted      = true

  # "Bỏ backup": Aurora requires backup_retention_period >= 1, so keep the
  # minimum (1 day) - it cannot be disabled entirely.
  backup_retention_period = 1
  skip_final_snapshot     = true
  apply_immediately       = true
  deletion_protection     = false

  tags = { Name = "${var.project_name}-Aurora-Primary" }

  # The global cluster owns engine/version; ignore so a managed minor-version
  # upgrade applied at the global level doesn't show as drift on the member.
  lifecycle {
    ignore_changes = [engine_version, replication_source_identifier]
  }
}


# -----------------------------------------------------------------------------
# 3. Cluster instances: 1 Writer + 2 Reader, one per AZ
# The first instance to come up becomes the writer; the rest are readers.
# Reads are load-balanced across all instances via the reader endpoint.
# -----------------------------------------------------------------------------
resource "aws_rds_cluster_instance" "members" {
  count              = var.instance_count
  identifier         = "${lower(var.project_name)}-aurora-${count.index + 1}"
  cluster_identifier = aws_rds_cluster.main.id

  instance_class = var.instance_class
  engine         = aws_rds_cluster.main.engine
  engine_version = aws_rds_cluster.main.engine_version

  db_subnet_group_name = var.db_subnet_group_name
  publicly_accessible  = false

  performance_insights_enabled = false

  tags = { Name = "${var.project_name}-Aurora-${count.index + 1}" }
}
